apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kps
    meta.helm.sh/release-namespace: prometheus
  labels:
    app.kubernetes.io/instance: kps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.0.1
    helm.sh/chart: grafana-9.2.2
  name: kps-grafana
  namespace: prometheus
  resourceVersion: "9064"
  uid: a100e22a-f5c5-49c3-bf9b-b68cbf95735d
spec:
  clusterIP: 10.43.69.9
  clusterIPs:
  - 10.43.69.9
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: kps
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
