apiVersion: v1
kind: Service
metadata:
  name: emby-service
spec:
  type: ClusterIP
  clusterIP: 10.43.69.12
  clusterIPs:
  - 10.43.69.12
  selector:
    app: emby
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8096